version: '3.8'

services:
  postgres:
    container_name: kasho_postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432

  postgres-live:
    container_name: kasho_postgres_live
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5433:5432